---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:5.6-jdk11
    environment:
      BINTRAY_USER:
        from_secret: BINTRAY_USER
      BINTRAY_TOKEN:
        from_secret: BINTRAY_TOKEN
    commands:
      - gradle clean compileJava test jacocoTestReport --info

  - name: trigger
    image: plugins/downstream
    settings:
      server: https://cloud.drone.io
      token:
        from_secret: DRONE_TOKEN
      fork: true
      repositories:
        - Romanow/scc-delivery
        - Romanow/scc-orders
    trigger:
      branch:
        - master
      event:
        - push

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: COVERAGE_TOKEN
      files:
        - report.xml
      paths:
        - build/reports/jacoco
      verbose: true